### ISSUE TITLE
hello world

### ISSUE THREAD

**Issue by ghost** [enovella/r2frida-wiki#2]
After r2 connect to frida server successfully, does it has all memory data maps in local  ?
In other words ,when I input "x" commnad ,does r2 load data in time from frida server ?

**Comment by enovella** [comment]
Yeah, r2 requests to Frida for this data. In order to do so, it uses the radare IO plugin. In the wiki are some commands to bring this info into r2land as flags. Check them out.

**Comment by ghost** [comment]
that is good ,but I have not found anything about r2land .
can you please give me some more details ?  
Does all data loaded at once ?
